import { useState } from 'react';

const GOLD = '#C8920A';

const OnboardingGuide = ({ content }) => {
  const [copied, setCopied] = useState(false);

  // Simple markdown parser — logic unchanged
  const parseMarkdown = (text) => {
    if (!text) return [];
    const lines = text.split('\n');
    const elements = [];
    let currentList = [];
    let currentCodeBlock = null;
    let inTable = false;
    let tableHeaders = [];
    let tableRows = [];

    const flushList = () => {
      if (currentList.length > 0) { elements.push({ type: 'list', items: [...currentList] }); currentList = []; }
    };
    const flushTable = () => {
      if (tableHeaders.length > 0) { elements.push({ type: 'table', headers: [...tableHeaders], rows: [...tableRows] }); tableHeaders = []; tableRows = []; inTable = false; }
    };

    lines.forEach((line) => {
      if (line.trim().startsWith('```')) {
        if (currentCodeBlock === null) {
          flushList(); flushTable();
          currentCodeBlock = { language: line.trim().slice(3), code: [] };
        } else {
          elements.push({ type: 'code', ...currentCodeBlock });
          currentCodeBlock = null;
        }
        return;
      }
      if (currentCodeBlock !== null) { currentCodeBlock.code.push(line); return; }

      if (line.startsWith('## ')) { flushList(); flushTable(); elements.push({ type: 'h2', text: line.slice(3) }); }
      else if (line.startsWith('### ')) { flushList(); flushTable(); elements.push({ type: 'h3', text: line.slice(4) }); }
      else if (line.startsWith('#### ')) { flushList(); flushTable(); elements.push({ type: 'h4', text: line.slice(5) }); }
      else if (line.includes('|') && line.trim().startsWith('|')) {
        flushList();
        const cells = line.split('|').map(c => c.trim()).filter(c => c);
        if (line.includes('---')) return;
        if (!inTable) { tableHeaders = cells; inTable = true; } else { tableRows.push(cells); }
      }
      else if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) { flushTable(); currentList.push(line.trim().slice(2)); }
      else if (line.trim().match(/^\d+\. /)) { flushTable(); currentList.push(line.trim().replace(/^\d+\.\s/, '')); }
      else if (line.trim()) { flushList(); flushTable(); elements.push({ type: 'p', text: line }); }
      else { flushList(); flushTable(); }
    });
    flushList(); flushTable();
    return elements;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => window.print();
  const elements = parseMarkdown(content);

  if (!content) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: 400 }}>
        <div style={{ textAlign: 'center', color: '#555' }}>
          <div style={{ fontSize: 48, marginBottom: 12 }}>📖</div>
          <p style={{ fontSize: 15 }}>No onboarding guide available</p>
        </div>
      </div>
    );
  }

  return (
    <div>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24, paddingBottom: 20, borderBottom: '1px solid #1A1A1A' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{ width: 38, height: 38, borderRadius: 10, background: '#1A1A1A', border: '1px solid #2A2A2A', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18 }}>📖</div>
          <div>
            <h2 style={{ color: '#fff', fontWeight: 700, fontSize: 16, margin: 0 }}>Onboarding Guide</h2>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 3 }}>
              <div style={{ width: 6, height: 6, borderRadius: '50%', background: GOLD }} />
              <span style={{ fontSize: 11, fontWeight: 700, color: GOLD }}>Generated by AI</span>
            </div>
          </div>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button
            onClick={handleCopy}
            style={{ padding: '7px 16px', borderRadius: 999, background: 'transparent', border: '1px solid #2A2A2A', color: '#A0A0A0', fontSize: 13, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6, transition: 'all 0.2s' }}
            onMouseOver={e => { e.currentTarget.style.borderColor = GOLD; e.currentTarget.style.color = '#fff'; }}
            onMouseOut={e =>  { e.currentTarget.style.borderColor = '#2A2A2A'; e.currentTarget.style.color = '#A0A0A0'; }}
          >
            {copied ? '✓ Copied' : 'Copy'}
          </button>
          <button
            onClick={handlePrint}
            style={{ padding: '7px 16px', borderRadius: 999, background: 'transparent', border: '1px solid #2A2A2A', color: '#A0A0A0', fontSize: 13, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6, transition: 'all 0.2s' }}
            onMouseOver={e => { e.currentTarget.style.borderColor = GOLD; e.currentTarget.style.color = '#fff'; }}
            onMouseOut={e =>  { e.currentTarget.style.borderColor = '#2A2A2A'; e.currentTarget.style.color = '#A0A0A0'; }}
          >
            Export PDF
          </button>
        </div>
      </div>

      {/* Content */}
      <div>
        {elements.map((el, i) => {
          switch (el.type) {
            case 'h2':
              return <h2 key={i} className="md-h2" style={{ color: GOLD }}>{el.text}</h2>;
            case 'h3':
              return <h3 key={i} className="md-h3">{el.text}</h3>;
            case 'h4':
              return <h4 key={i} className="md-h4">{el.text}</h4>;
            case 'p':
              return <p key={i} className="md-p">{el.text}</p>;
            case 'list':
              return (
                <ul key={i} style={{ paddingLeft: 20, margin: '0 0 14px' }}>
                  {el.items.map((item, j) => (
                    <li key={j} className="md-li">• {item}</li>
                  ))}
                </ul>
              );
            case 'code':
              return (
                <div key={i} style={{ marginBottom: 16 }}>
                  {el.language && (
                    <div style={{ background: '#0d1117', borderRadius: '8px 8px 0 0', padding: '7px 14px', border: '1px solid #21262d', borderBottom: 'none' }}>
                      <span className="md-code-lang">{el.language}</span>
                    </div>
                  )}
                  <pre style={{
                    margin: 0, background: '#0d1117',
                    border: '1px solid #21262d',
                    borderRadius: el.language ? '0 0 8px 8px' : 8,
                    padding: '14px 16px', overflowX: 'auto',
                    fontSize: 12.5, lineHeight: 1.65, color: '#e6edf3',
                    fontFamily: '"JetBrains Mono","Fira Code",Consolas,monospace',
                  }}>
                    <code>{el.code.join('\n')}</code>
                  </pre>
                </div>
              );
            case 'table':
              return (
                <div key={i} style={{ overflowX: 'auto', marginBottom: 20 }}>
                  <table style={{ width: '100%', borderCollapse: 'collapse', background: '#0d1117', borderRadius: 10, overflow: 'hidden' }}>
                    <thead>
                      <tr style={{ background: '#111' }}>
                        {el.headers.map((h, j) => (
                          <th key={j} className="md-table-th">{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {el.rows.map((row, j) => (
                        <tr key={j}>
                          {row.map((cell, k) => (
                            <td key={k} className="md-table-td">{cell}</td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              );
            default: return null;
          }
        })}
      </div>
    </div>
  );
};

export default OnboardingGuide;
