import { useState } from 'react';

const OnboardingGuide = ({ content }) => {
  const [copied, setCopied] = useState(false);

  // Simple markdown parser
  const parseMarkdown = (text) => {
    if (!text) return [];
    
    const lines = text.split('\n');
    const elements = [];
    let currentList = [];
    let currentCodeBlock = null;
    let inTable = false;
    let tableHeaders = [];
    let tableRows = [];

    const flushList = () => {
      if (currentList.length > 0) {
        elements.push({ type: 'list', items: [...currentList] });
        currentList = [];
      }
    };

    const flushTable = () => {
      if (tableHeaders.length > 0) {
        elements.push({ type: 'table', headers: [...tableHeaders], rows: [...tableRows] });
        tableHeaders = [];
        tableRows = [];
        inTable = false;
      }
    };

    lines.forEach((line, index) => {
      // Code blocks
      if (line.trim().startsWith('```')) {
        if (currentCodeBlock === null) {
          flushList();
          flushTable();
          currentCodeBlock = { language: line.trim().slice(3), code: [] };
        } else {
          elements.push({ type: 'code', ...currentCodeBlock });
          currentCodeBlock = null;
        }
        return;
      }

      if (currentCodeBlock !== null) {
        currentCodeBlock.code.push(line);
        return;
      }

      // Headers
      if (line.startsWith('## ')) {
        flushList();
        flushTable();
        elements.push({ type: 'h2', text: line.slice(3) });
      } else if (line.startsWith('### ')) {
        flushList();
        flushTable();
        elements.push({ type: 'h3', text: line.slice(4) });
      } else if (line.startsWith('#### ')) {
        flushList();
        flushTable();
        elements.push({ type: 'h4', text: line.slice(5) });
      }
      // Table detection
      else if (line.includes('|') && line.trim().startsWith('|')) {
        flushList();
        const cells = line.split('|').map(c => c.trim()).filter(c => c);
        
        if (line.includes('---')) {
          // Skip separator line
          return;
        }
        
        if (!inTable) {
          tableHeaders = cells;
          inTable = true;
        } else {
          tableRows.push(cells);
        }
      }
      // Lists
      else if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
        flushTable();
        currentList.push(line.trim().slice(2));
      } else if (line.trim().startsWith(/\d+\. /)) {
        flushTable();
        currentList.push(line.trim().replace(/^\d+\.\s/, ''));
      }
      // Paragraphs
      else if (line.trim()) {
        flushList();
        flushTable();
        elements.push({ type: 'p', text: line });
      } else {
        flushList();
        flushTable();
      }
    });

    flushList();
    flushTable();
    return elements;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const elements = parseMarkdown(content);

  if (!content) {
    return (
      <div className="flex items-center justify-center h-full min-h-[400px] text-gray-400">
        <div className="text-center">
          <svg className="w-16 h-16 mx-auto mb-4 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <p className="text-lg">No onboarding guide available</p>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full h-full">
      {/* Header */}
      <div className="flex items-center justify-between mb-6 pb-4 border-b border-gray-800">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gradient-to-br from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
            <svg className="w-6 h-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
            </svg>
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">Onboarding Guide</h2>
            <div className="flex items-center gap-2 mt-1">
              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              <span className="text-xs text-blue-400 font-semibold">Generated by IBM Bob</span>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className="px-4 py-2 bg-gray-800 hover:bg-gray-700 border border-gray-700 text-white rounded-lg transition-all duration-200 flex items-center gap-2"
          >
            {copied ? (
              <>
                <svg className="w-4 h-4 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                Copy
              </>
            )}
          </button>
          <button
            onClick={handlePrint}
            className="px-4 py-2 bg-gray-800 hover:bg-gray-700 border border-gray-700 text-white rounded-lg transition-all duration-200 flex items-center gap-2"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Export PDF
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="prose prose-invert max-w-none markdown-content">
        {elements.map((element, index) => {
          switch (element.type) {
            case 'h2':
              return (
                <h2 key={index} className="text-2xl font-bold gradient-text mb-4 mt-8">
                  {element.text}
                </h2>
              );
            case 'h3':
              return (
                <h3 key={index} className="text-xl font-semibold text-white mb-3 mt-6">
                  {element.text}
                </h3>
              );
            case 'h4':
              return (
                <h4 key={index} className="text-lg font-semibold text-gray-300 mb-2 mt-4">
                  {element.text}
                </h4>
              );
            case 'p':
              return (
                <p key={index} className="text-gray-300 mb-4 leading-relaxed">
                  {element.text}
                </p>
              );
            case 'list':
              return (
                <ul key={index} className="list-disc list-inside space-y-2 mb-4 text-gray-300">
                  {element.items.map((item, i) => (
                    <li key={i} className="ml-4">{item}</li>
                  ))}
                </ul>
              );
            case 'code':
              return (
                <div key={index} className="mb-4">
                  {element.language && (
                    <div className="bg-gray-800 px-4 py-2 rounded-t-lg border-b border-gray-700">
                      <span className="text-xs font-semibold text-blue-400 uppercase">{element.language}</span>
                    </div>
                  )}
                  <pre className={`bg-gray-900 p-4 ${element.language ? 'rounded-b-lg' : 'rounded-lg'} overflow-x-auto border border-gray-700`}>
                    <code className="text-sm text-gray-300 font-mono">
                      {element.code.join('\n')}
                    </code>
                  </pre>
                </div>
              );
            case 'table':
              return (
                <div key={index} className="mb-6 overflow-x-auto">
                  <table className="w-full border-collapse bg-gray-900 rounded-lg overflow-hidden">
                    <thead>
                      <tr className="bg-gray-800">
                        {element.headers.map((header, i) => (
                          <th key={i} className="px-4 py-3 text-left text-sm font-semibold text-blue-400 border-b border-gray-700">
                            {header}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {element.rows.map((row, i) => (
                        <tr key={i} className="border-b border-gray-800 hover:bg-gray-800/50 transition-colors">
                          {row.map((cell, j) => (
                            <td key={j} className="px-4 py-3 text-sm text-gray-300">
                              {cell}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              );
            default:
              return null;
          }
        })}
      </div>
    </div>
  );
};

export default OnboardingGuide;

// Made with Bob
